[package]
name = "velos-log-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
velos-core = { path = "../velos-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
thiserror = "2"
